study_dir: "/home/xuewei/MRI/UCSF_PDGM_flat"
output_dir: "/home/xuewei/MRI/UCSF_PDGM_flat_prima"
tokenizer_model_config: "/home/xuewei/MRI/Prima/test/trained_models/tokenizer_model/config.json"
prima_model_config: "/home/xuewei/MRI/Prima/test/trained_models/prima_config.json"
batch_size: 1
device: "cuda"
num_workers: 0
